# Generated by Django 5.2 on 2025-04-25 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_availability_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='Event',
        ),
    ]
