# Generated by Django 5.2 on 2025-04-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_rename_availability_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
