# Generated by Django 5.2 on 2025-04-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
