# Generated by Django 5.2 on 2025-04-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0005_remove_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
