# Generated by Django 5.2 on 2025-04-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0006_remove_event_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Mes évènements',
        ),
    ]
